### ISSUE TITLE
Problem building application from source

### ISSUE THREAD

**Issue by Eonevsg** [gophish/gophish#2768]
**What version of Gophish are you using?:** 
Gophish version - 0.12.1
$ go version
go version go1.20 windows/amd64

**Brief description of the issue:** 
Upon trying to build application from source it fails during download stage.

**What are you expecting to see happen? :**
I am expecting command that is written in documentation to finish successfully

**What are you seeing happen?**
After running a command I saw 'go' tried to download packages from github etc.

**Please provide any terminal output that may be relevant below:**

```
$ go install github.com/gophish/gophish@latest
go: downloading github.com/gophish/gophish v0.12.1
go: downloading github.com/gorilla/sessions v1.2.0
go: downloading github.com/gorilla/csrf v1.6.2
go: downloading github.com/gorilla/securecookie v1.1.1
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading github.com/gorilla/mux v1.7.3
go: downloading github.com/jordan-wright/unindexed v0.0.0-20181209214434-78fa79113c0f
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/NYTimes/gziphandler v1.1.1
go: downloading github.com/emersion/go-imap v1.0.4
go: downloading github.com/emersion/go-message v0.12.0
go: downloading github.com/jordan-wright/email v4.0.1-0.20200824153738-3f5bafa1cd84+incompatible
go: downloading bitbucket.org/liamstask/goose v0.0.0-20150115234039-8488cc47d90c
go: downloading github.com/PuerkitoBio/goquery v1.5.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gophish/gomail v0.0.0-20200818021916-1f6d0dfd512e
go: downloading github.com/jinzhu/gorm v1.9.12
go: downloading github.com/mattn/go-sqlite3 v2.0.3+incompatible
go: downloading github.com/oschwald/maxminddb-golang v1.6.0
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading golang.org/x/crypto v0.0.0-20200128174031-69ecbb4d6d5d
go: downloading golang.org/x/time v0.0.0-20200416051211-89c76fbcd5d1
go: downloading github.com/pkg/errors v0.8.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/kylelemons/go-gypsy v0.0.0-20160905020020-08cad365cd28
go: downloading github.com/lib/pq v1.1.1
go: downloading github.com/ziutek/mymysql v1.5.4
go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
go: downloading github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d
go: downloading github.com/emersion/go-sasl v0.0.0-20191210011802-430746ea8b9b
go: downloading golang.org/x/sys v0.0.0-20191224085550-c709ea063b76
go: downloading github.com/andybalholm/cascadia v1.0.0
go: downloading golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: downloading github.com/jinzhu/inflection v1.0.0
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: downloading github.com/emersion/go-textwrapper v0.0.0-20160606182133-d0e65e56babe
# bitbucket.org/liamstask/goose/lib/goose
C:\Users\e1\go\pkg\mod\bitbucket.org\liamstask\goose@v0.0.0-20150115234039-8488cc47d90c\lib\goose\dialect.go:119:15: undefined: sqlite3.Error
```

**Please provide as many steps as you can to reproduce the problem:**
 * Step 1 - I donwloaded golang from go.dev for microsoft windows and installed it
 * Step 2 - Tried running 'go install github.com/gophish/gophish@latest' command and it failed with output that is provided above
 
 I also tried using Linux,
 Ubuntu 20.04.3 LTS,
 Kernel: Linux 5.11.0-27-generic,
 Architecture: x86-64  
 but it also fails with the same error.

**Comment by glennzw** [comment]
Please see the [README.md](https://github.com/gophish/gophish/blob/master/README.md) file for building from source:

----

### Building From Source
**If you are building from source, please note that Gophish requires Go v1.10 or above!**

To build Gophish from source, simply run ```git clone https://github.com/gophish/gophish.git``` and ```cd``` into the project source directory. Then, run ```go build```. After this, you should have a binary called ```gophish``` in the current directory.

----

**Comment by Eonevsg** [comment]
I did exactly what is written in the documentation, but it doesn't work. Can You try Yourself?

**Comment by glennzw** [comment]
Just double checking; in your issue you said you tried installing with `go install github.com/gophish/gophish@latest`, rather than what I suggested above.

**Comment by Eonevsg** [comment]
After You commented, I followed those steps:
1. git clone https://github.com/gophish/gophish.git
2. go build

Still got the same error

**Comment by glennzw** [comment]
OK cool thanks - I'll try reproduce.

**Comment by Eonevsg** [comment]
I don't want to apear pushy, but I am curious whether you managed to reproduce this error?

**Comment by glennzw** [comment]
In a Docker container I compiled successfully:

```
# cat /etc/issue
Debian GNU/Linux 11 \n \l

# go version
go version go1.19 linux/arm64
# go build 
# ./gophish
```

Difference here being the Linux distro and go version.

One thing that has tripped people up, try this before running `go build`:

`export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"`

I'll grab a `Ubuntu 20.04` now to try reproduce with your OS.

**Comment by Eonevsg** [comment]
My very first try was on Windows 10 with go version go1.20 windows/amd64 and I wasn't using Docker. I will try with export and then Debian with go version go1.19.

I would be more instested to run in on Windows than on Linux, to be honest.

**Comment by glennzw** [comment]
Good (bad!) news - I'm able to reproduce the issue:

```bash
# cat /etc/issue
Ubuntu 20.04.4 LTS
# uname -a
Linux ubuntu-s-1vcpu-2gb-lon1-01 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# go version
go version go1.20.1 linux/amd64

# git clone https://github.com/gophish/gophish
Cloning into 'gophish'...
remote: Enumerating objects: 8044, done.
remote: Counting objects: 100% (18/18), done.
....

# cd gophish/
# go build
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/NYTimes/gziphandler v1.1.1
go: downloading github.com/gorilla/csrf v1.6.2
....
go: downloading github.com/emersion/go-textwrapper v0.0.0-20160606182133-d0e65e56babe
# bitbucket.org/liamstask/goose/lib/goose
../go/pkg/mod/bitbucket.org/liamstask/goose@v0.0.0-20150115234039-8488cc47d90c/lib/goose/dialect.go:119:15: undefined: sqlite3.Error
```

With go v1.19 I have success on the same machine, but only after installing gcc for some reason (`apt install gcc`):

```bash
# go version
go version go1.19 linux/amd64

# go build
# ./gophish 
time="2023-02-17T21:57:13Z" level=warning msg="No contact address has been configured."
time="2023-02-17T21:57:13Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: migrating db environment 'production', current version: 0, target: 20220321133237
OK    20160118194630_init.sql
OK    20160131153104_0.1.2_add_event_details.sql
OK    20160211211220_0.1.2_add_ignore_cert_errors.sql
OK    20160217211342_0.1.2_create_from_col_results.sql
OK    20160225173824_0.1.2_capture_credentials.sql
OK    20160227180335_0.1.2_store-smtp-settings.sql
OK    20160317214457_0.2_redirect_url.sql
OK    20160605210903_0.2_campaign_scheduling.sql
OK    20170104220731_0.2_result_statuses.sql
.....
```

.... and actually now that it works with 1.19, it also works with 1.20. I think there's something funny going on with cross compiling and sqlite.

**Comment by glennzw** [comment]
Can confirm the following solved the problem:

`apt install gcc`

Full output on a brand new machine matching yours:

```bash
# cat /etc/issue
Ubuntu 20.04.4 LTS
# uname -a
Linux ubuntu-s-1vcpu-2gb-lon1-01 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# go version
go version go1.20.1 linux/amd64
# apt-get update
# apt install gcc
# wget https://dl.google.com/go/go1.20.1.linux-amd64.tar.gz
# tar -C /usr/local -xvf go1.20.1.linux-amd64.tar.gz
# echo "export PATH=\$PATH:/usr/local/go/bin" >> $HOME/.profile
# # git clone https://github.com/gophish/gophish
Cloning into 'gophish'...
remote: Enumerating objects: 8044, done.
remote: Counting objects: 100% (18/18), done.
....

# cd gophish/
# go build
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/NYTimes/gziphandler v1.1.1
go: downloading github.com/gorilla/csrf v1.6.2
....
go: downloading github.com/emersion/go-textwrapper v0.0.0-20160606182133-d0e65e56babe
# ./gophish
time="2023-02-17T22:22:17Z" level=warning msg="No contact address has been configured."
time="2023-02-17T22:22:17Z" level=warning msg="Please consider adding a contact_address entry in your config.json"
goose: no migrations to run. current version: 20220321133237
time="2023-02-17T22:22:18Z" level=info msg="Please login with the username admin and the password 9e3c6a92a47cbcf1"
time="2023-02-17T22:22:18Z" level=info msg="Starting admin server at https://127.0.0.1:3333"
time="2023-02-17T22:22:18Z" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
time="2023-02-17T22:22:18Z" level=info msg="Starting IMAP monitor manager"
time="2023-02-17T22:22:18Z" level=info msg="Starting new IMAP monitor for user admin"
time="2023-02-17T22:22:18Z" level=info msg="Starting phishing server at http://0.0.0.0:80"
```

**Comment by Eonevsg** [comment]
Want to inform, that Your adviced configuration (Debian plus go1.19) worked for me too.

**Comment by glennzw** [comment]
Great, I'll close this out.
